---
- name: Create AWS S3 Bucket
  hosts: localhost
  vars:
    encryption_type: "AES256"
  tasks:
    - name: Create bucket without JSON policy
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        encryption: "{{ encryption_type }}"
      register: created_bucket
