apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: aws-sqs-batch-sink-pipe
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: aws-sqs-batch-sink
    properties:
      accessKey: "The Access Key"
      batchSeparator: ","
      queueNameOrArn: "The Queue Name"
      region: "eu-west-1"
      secretKey: "The Secret Key"
  