apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: azure-cosmosdb-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: azure-cosmosdb-source
    properties:
      accountKey: "The Account Key"
      containerName: "The Container Name"
      databaseEndpoint: "The Database Endpoint"
      databaseName: "The Database Name"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  