apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: cron-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: cron-source
    properties:
      message: "hello world"
      schedule: "0/3 10 * * * ?"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  