apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: fhir-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: fhir-source
    properties:
      password: "The Password"
      serverUrl: "The Server URL"
      username: "The Username"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  