apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: file-watch-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: file-watch-source
    properties:
      filePath: "The Path to Watch"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  