apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: github-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: github-source
    properties:
      oauthToken: "The OAuth Token"
      repoName: "The Repository Name"
      repoOwner: "The Repository Owner"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  