apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: google-pubsub-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: google-pubsub-source
    properties:
      projectId: "The Project Id"
      serviceAccountKey: "The Service Account Key"
      subscriptionName: "The Subscription Name"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  