apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: google-pubsub-sink-pipe
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: google-pubsub-sink
    properties:
      destinationName: "The Destination Name"
      projectId: "The Project Id"
      serviceAccountKey: "The Service Account Key"
  