apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: infinispan-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: infinispan-source
    properties:
      cacheName: "The Cache Name"
      hosts: "The Hosts"
      password: "The Password"
      username: "The Username"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  