apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: jms-amqp-10-ssl-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jms-amqp-10-ssl-source
    properties:
      destinationName: "The Destination Name"
      remoteURI: "amqps://my-host:5671?transport.trustStoreLocation=/path/to/truststore.jks&transport.trustStorePassword=changeit"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
