apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: kafka-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kafka-source
    properties:
      bootstrapServers: "The Bootstrap Servers"
      topic: "The Topic Names"
      saslAuthType: "NONE"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
