apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: kubernetes-nodes-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: kubernetes-nodes-source
    properties:
      masterUrl: "The Kubernetes Master URL"
      token: "The Oauth Token"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  