apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: mail-sink-pipe
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: mail-sink
    properties:
      connectionHost: "smtp.gmail.com"
      password: "The Password"
      username: "The Username"
  