apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: minio-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: minio-source
    properties:
      accessKey: "The Access Key"
      bucketName: "The Bucket Name"
      endpoint: "http://localhost:9000"
      secretKey: "The Secret Key"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  