apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: mqtt-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: mqtt-source
    properties:
      brokerUrl: "tcp://mosquitto:1883"
      topic: "mytopic"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  