apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: pulsar-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: pulsar-source
    properties:
      namespaceName: "The Pulsar Namespace Name"
      serviceUrl: "The Service URL"
      tenant: "The Tenant Name"
      topic: "The Topic Name"
      topicType: "The Topic Type"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  