apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: websocket-source-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: websocket-source
    properties:
      resourceUri: "The Resource Uri"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  