apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: chuck-norris-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: chuck-norris-source
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  