apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: jms-apache-artemis-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-apache-artemis-sink
    properties:
      brokerURL: "tcp://my-host:61616"
      destinationName: "person"
  