apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: nats-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: nats-source
    properties:
      servers: "The Servers"
      topic: "The Topic"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  