apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: rabbitmq-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: rabbitmq-source
    properties:
      addresses: "The Addresses"
      exchangeName: "The Exchange name"
      password: "The Password"
      username: "The Username"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  