apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: ssh-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: ssh-source
    properties:
      connectionHost: "The Connection Host"
      password: "The Password"
      pollCommand: "date"
      username: "The Username"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  