= Kamelet Catalog

[NOTE]
--
This version ({page-component-display-version}) of {page-component-title} depends on:

* xref:{camel-docs-version}@components::index.adoc[Camel] at version {camel-version}

ifndef::version-used[It is not currently used by other subprojects such as camel-k or camel-kafka-connector.]
ifdef::version-used[]
It is used by:

ifdef::camel-k-version[]
* xref:{camel-k-docs-version}@camel-k::index.adoc[Camel-K] at version {camel-k-version}
endif::[]
ifdef::camel-kafka-connector-version[]
* xref:{camel-kafka-connector-docs-version}@camel-kafka-connector::index.adoc[Camel Kafka Connector] at version {camel-kafka-connector-version}
endif::[]

endif::[]

ifdef::lts[This long term service release will be supported until {lts}.]
ifndef::lts[]
ifdef::prerelease[This is the development version of {page-component-title}. It should not be used in production.]
ifndef::prerelease[This release will not be updated, but rather replaced by a new release.]
endif::[]
--

This page contains the default Apache Camel Kamelets catalog.

Consult the xref:{camel-k-docs-version}@camel-k::kamelets/kamelets-user.adoc[Kamelets User Guide] for information about how to use these.

**We love contributions for this catalog**: you can follow the xref:{camel-k-docs-version}@camel-k::kamelets/kamelets-dev.adoc[Kamelets Developer Guide]
for information on how to create new Kamelets and contribute them to the official https://github.com/apache/camel-kamelets/[github.com/apache/camel-kamelets] repository.

[indexBlock,'xref=$xref']
----
[.catalog]
[.item]#{xref}#

----
