= Kamelet Catalog

== Kamelet specification

Kamelets were originally born for Kubernetes and they have eventually moved to be used as Camel core resources. Its specification is a Kubernetes CRD specification. You can use it in your project by using Maven dependency `org.apache.camel.kamelets:camel-kamelets-crds`.

== Development guide

Kamelets are extensible components. Look at the guide and learn xref:development.adoc[how to develop a new Kamelet].

== Compatibility Matrix

[caption=]
.Compatibility between Kamelets catalog and related subprojects
[width="100%",cols="4,2,1,3",options="header"]
|===
|Camel-Kamelets Version
|Using Camel Version
|LTS Until
|Branch
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="avro-deserialize-action.adoc",cellformats="util.kameletsRef(pageComponentDisplayVersion, pageComponentVersion)|util.camelRef(camelVersion, camelDocsVersion)|lts|kamelets.branch(pageComponentVersion)", requires={requires},transform=util.sortCompatibilityItems]

This page contains the default Apache Camel Kamelets catalog.

Consult the Kamelets User Guide for information about how to use these.

**We love contributions for this catalog**: you can follow the Kamelets Developer Guide for information on how to create new Kamelets and contribute them to the official https://github.com/apache/camel-kamelets/[github.com/apache/camel-kamelets] repository.

[indexBlock,'xref=$xref']
----
[.catalog]
[.item]#{xref}#

----
