== Azure Storage Queue Source Kamelet Description

=== Authentication methods

In this Kamelet, you can use these Azure authentication methods:

- Azure Identity mechanism:  `AZURE_IDENTITY`
- Plain Shared Account Key:  `SHARED_ACCOUNT_KEY`
- Shared Key Credentials:  `SHARED_KEY_CREDENTIAL`

The default is SHARED_ACCOUNT_KEY.

The order of evaluation for `AZURE_IDENTITY` is the following:

 - Enviroment
 - Workload Identity 
 - Managed Identity 
 - Azure Developer CLI 
 - IntelliJ
 - Azure CLI
 - Azure Powershell

For more information, see the https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme[Azure Identity documentation]

=== Optional Headers

In the header, you can set the `partition` / `ce-partition` property to determine how long an event remains in the Azure Storage queue. Use `PnDTnHnMn.nS.` format. For example, `PT20.345S` parses as 20.345 seconds and `P2D` parses as 2 days. If you not set the property in the header, the Kamelet uses the default of `P27D` (7 days).
