Parameters:
  BucketName:
    Type: String
    Description: The bucket name.

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: 
        Ref: BucketName
