apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: azure-eventhubs-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: azure-eventhubs-sink
    properties:
      eventhubName: "The Eventhubs Name"
      namespaceName: "The Eventhubs Namespace"
      sharedAccessKey: "The Share Access Key"
      sharedAccessName: "The Share Access Name"
  