apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: elasticsearch-search-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: elasticsearch-search-source
    properties:
      clusterName: "The ElasticSearch Cluster Name"
      hostAddresses: "The Host Addresses"
      indexName: "The Index in ElasticSearch"
      query: "The Query"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  