apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: github-tag-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: github-tag-source
    properties:
      oauthToken: "The OAuth Token"
      repoName: "The Repository Name"
      repoOwner: "The Repository Owner"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  