apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: google-storage-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: google-storage-sink
    properties:
      bucketNameOrArn: "The Bucket Name Or ARN"
      serviceAccountKey: "The Service Account Key"
  