apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: google-functions-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: google-functions-sink
    properties:
      functionName: "The Function Name"
      projectId: "The Project Id"
      serviceAccountKey: "The Service Account Key"
  