apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mail-imap-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: mail-imap-source
    properties:
      connectionHost: "imap.gmail.com"
      password: "The Password"
      username: "The Username"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  