apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: mqtt-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-sink
    properties:
      brokerUrl: "tcp://mosquitto:1883"
      topic: "mytopic"
  