apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: pulsar-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: pulsar-sink
    properties:
      namespaceName: "The Pulsar Namespace Name"
      serviceUrl: "The Service URL"
      tenant: "The Tenant Name"
      topic: "The Topic Name"
      topicType: "The Topic Type"
  