apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: rabbitmq-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: rabbitmq-source
    properties:
      addresses: "localhost:5672"
      exchangeName: "The Exchange name"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  