apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: redis-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: redis-source
    properties:
      redisHost: "The Redis Host"
      redisPort: "The Redis Port"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  