apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: solr-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: solr-source
    properties:
      collection: "The Collection"
      query: "The Query"
      servers: "The Servers"
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  