apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: splunk-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: splunk-sink
    properties:
      serverHostname: "<splunk server>"
      username: "admin"
      sourceType: grok
      password: "<password>"
