apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: splunk-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: splunk-source
    properties:
      serverHostname: "splunk address"
      username: "admin"
      password: "password"
      query: "search Code=D | head 5"
      initEarliestTime: "08/17/13 08:35:46:456"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
