apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: ssh-sink-binding
spec:
  source:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: ssh-sink
    properties:
      connectionHost: "The Connection Host"
      password: "The Password"
      username: "The Username"
  